Avoid error undef error in Gem::Specification
This method was removed in rubygems v4.0.0 [1], so it should only be undefined
if it is acutally defined to avoid an exception like this:

    NameError: undefined method 'has_rdoc?' for class 'Gem::Specification'

[1]: https://github.com/ruby/rubygems/blob/e7cb04353fc8fe85d359d34d9d467d17d33bdbd3/CHANGELOG.md#breaking-changes