Fix constant lookup for Parser::Ruby::RubyParser
Previously I was seeing errors like this when running this spec:

    NameError: uninitialized constant YARD::Tags::TypesExplainer::Parser::Ruby

Ruby v4.0 seems to have changed constant lookup slightly so the less-qualified
constant wasn't working any more. The fully-qualified version was already being
used in other specs, so this make the specs more consistent.