spec: Skip markdown-specific test with 'pending'.
Fixes this error which happens when running the tests without the redcarpet gem installed:
```
Failures:

  1) YARD::Templates::Helpers::HtmlHelper#htmlify creates tables (markdown specific)
     Failure/Error: skip "This test depends on a markdown engine that supports tables"
     NoMethodError:
       undefined method `skip' for #<RSpec::Core::ExampleGroup::Nested_122::Nested_4:0x0055555a184840>
     # ./spec/templates/helpers/html_helper_spec.rb:187:in `block (4 levels) in <top (required)>'
     # ./lib/yard/logging.rb:168:in `enter_level'
     # ./spec/templates/helpers/html_helper_spec.rb:185:in `block (3 levels) in <top (required)>'
```